sudo: false  # access to caching
language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache
  #- mpich
  - petsc

env:

  global:
    #

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libmpich-dev
      # - libnuma-dev
      - lcov
      - doxygen

before_install:
  #- sh ./get_mpich.sh
  - sh ./get_petsc.sh

install:
  #

script:
  - export PETSC_DIR=$HOME/build/dbeat/numerical/petsc
  - export PETSC_ARCH=arch-linux2-c-debug
  - echo $PETSC_DIR
  - sh ./build.sh  # build project

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' '*/tests/*' '*/third_party/*' --output-file coverage.info
# output coverage data for debugging
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

# https://github.com/EmaroLab/docs/wiki/Automatic-deployment-Doxygen-documentation
# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master


notifications:
  email:
    - frns.roy@gmail.com
